"""
email_sender.py — Sends business reports via Gmail SMTP.
Uses App Password authentication; never use your real Gmail password.
"""

import os
import smtplib
import ssl
from email.message import EmailMessage
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# === Configuration ===
GMAIL_ADDRESS = os.getenv("GMAIL_ADDRESS")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 465  # SSL port

if not GMAIL_ADDRESS or not GMAIL_APP_PASSWORD:
    raise RuntimeError(
        "GMAIL_ADDRESS or GMAIL_APP_PASSWORD missing from .env file. "
        "Make sure both are set."
    )


def send_report_email(
    recipients: list[str],
    subject: str,
    body: str,
    sender: str = None,
) -> None:
    """
    Send the report as a plain-text email to one or more recipients.

    Args:
        recipients: List of email addresses.
        subject: Email subject line.
        body: Email body (plain text).
        sender: Optional override for FROM address. Defaults to GMAIL_ADDRESS.

    Raises:
        RuntimeError: If sending fails for any reason.
    """
    if not recipients:
        raise ValueError("Recipients list cannot be empty")

    from_address = sender or GMAIL_ADDRESS

    msg = EmailMessage()
    msg["From"] = from_address
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject
    msg.set_content(body)

    context = ssl.create_default_context()

    try:
        with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, context=context) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.send_message(msg)
    except smtplib.SMTPAuthenticationError as e:
        raise RuntimeError(
            f"Gmail authentication failed: {e}\n"
            "Check that GMAIL_APP_PASSWORD is correct in .env "
            "(use the App Password, NOT your regular Gmail password)."
        ) from e
    except Exception as e:
        raise RuntimeError(f"Failed to send email: {e}") from e


def build_subject(date_str: str = None) -> str:
    """Generate a clean subject line for the daily report."""
    if not date_str:
        date_str = datetime.now().strftime("%b %d, %Y")
    return f"Daily Business Report — {date_str}"


if __name__ == "__main__":
    # Test with a simple message
    test_recipient = input("Enter your email to test send: ").strip()

    if not test_recipient:
        print("No recipient provided. Exiting.")
        exit(1)

    print(f"\nSending test email to {test_recipient}...")

    send_report_email(
        recipients=[test_recipient],
        subject=build_subject() + " (TEST)",
        body=(
            "This is a test email from your AI Business Report Generator.\n\n"
            "If you're reading this, your email setup is working correctly!\n\n"
            "—\nGenerated by ai-business-report-generator"
        ),
    )

    print("✓ Test email sent successfully.")
    print("Check your inbox (and spam folder, just in case).")